apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pinktomato-deploy
  name: pinktomato-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pinktomato-deploy
  template:
    metadata:
      labels:
        app: pinktomato-deploy
    spec:
      containers:
      - image: tomato157/furbabies:latest
        name: pet
